// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeMatcher.Infrastructure;

#nullable disable

namespace ResumeMatcher.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResumeMatcherDbContext))]
    [Migration("20260907082529_AddResumeOptimization")]
    partial class AddResumeOptimization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeMatcher.Domain.AnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisInputHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EducationScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ExperienceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("RequirementsScore")
                        .HasColumnType("double precision");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<double>("SeniorityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("SkillsScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("OwnerUserId", "AnalysisInputHash")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "ResumeId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("ResumeMatcher.Domain.ResumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeMatcher.Domain.ResumeOptimizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdaptedText")
                        .HasColumnType("text");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionsJson")
                        .HasColumnType("text");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SuggestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("OwnerUserId", "AnalysisId");

                    b.HasIndex("OwnerUserId", "ResumeId");

                    b.ToTable("Optimizations");
                });

            modelBuilder.Entity("ResumeMatcher.Domain.AnalysisEntity", b =>
                {
                    b.HasOne("ResumeMatcher.Domain.ResumeEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId", "ResumeId")
                        .HasPrincipalKey("OwnerUserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeMatcher.Domain.ResumeOptimizationEntity", b =>
                {
                    b.HasOne("ResumeMatcher.Domain.AnalysisEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId", "AnalysisId")
                        .HasPrincipalKey("OwnerUserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeMatcher.Domain.ResumeEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId", "ResumeId")
                        .HasPrincipalKey("OwnerUserId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
